version: '3.8'

services:
  web:
    build:
      context: . 
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/app/app
    environment:
      - DB_HOST=db
      - APP_VERSION=v1.0.0-dev

  db:
    image: postgres:14-alpine 
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=maindb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
