- name: Deploy Dockerized Application
  hosts: all
  become: true 
  vars:
    dockerhub_username: your_dockerhub_username 
    repo_name: python-cicd-project 

  tasks:
    - name: Install required system packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'python3-pip']
        state: present
        update_cache: yes

    - name: Install Docker and Docker Compose
      pip:
        name: ['docker', 'docker-compose']

    - name: Pull latest image from Docker Hub
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/{{ repo_name }}:latest"
        source: pull

    - name: Stop and remove existing container to ensure a fresh start
      community.docker.docker_container:
        name: python-app-container
        state: absent

    - name: Run the new container
      community.docker.docker_container:
        name: python-app-container
        image: "{{ dockerhub_username }}/{{ repo_name }}:latest"
        state: started
        restart_policy: always
        ports:
          - "80:5000" 
        env:
          APP_VERSION: "v1.0.0-prod"
          DB_HOST: "production-db-hostname"